apiVersion: batch/v1
kind: Job
metadata:
  name: loaderJob
spec:
  template:
    metadata:
      name: loaderJob
    spec:
      containers:
      - name: database
        image: python
        command:oc new-app https://github.com/rebeccaSimmonds19/WineMapDatabase.git \
          --name database \
          -e server='postgresql' \
          -e user='username' \
          -e password='password' \
          -e dbname='wineDb'
      restartPolicy: Never
