apiVersion: batch/v1
kind: Job
metadata:
  name: loaderjob
spec:
  template:
    metadata:
      name: loaderjob
    spec:
      containers:
      - name: loaderjob
        image: python
        command: ["oc new-app https://github.com/rebeccaSimmonds19/WineMapDatabase.git --name database -e server='postgresql'-e user='username' -e password='password' -e dbname='wineDb'"]
    restartPolicy: OnFailure
