apiVersion: batch/v1
kind: Job
metadata:
  name: loader
spec:
  template:
    metadata:
      name: loader
    spec:
      containers:
      - name: loader
        image: python
        command: ["python", "loader.py"]
      restartPolicy: Never
